### ISSUE TITLE
Some extra C# overloads/defaults

### ISSUE THREAD

**Issue by benjstephenson** [jet/propulsion#191]
Using the library from a C# project has been pretty straightforward, but there are a couple of `Func -> FSharpFunc` conversions that add a bit of noise.  I think the main one is the `handle` parameter passed to `StreamsProjector.Start`

I can see the signature is
 `FSharpFunc<Tuple<string, StreamSpan<byte[]>>, FSharpAsync<Tuple<SpanResult, Outcome>>> handle`

so to get the application code to play nice I have to do something like:

```csharp
    public Func<Tuple<string, StreamSpan<byte[]>>, FSharpAsync<Tuple<SpanResult, Outcome>>> Handle =>
        args =>
            FSharpAsync.AwaitTask(
                Aggregate.Reactions.Parse(args.Item1, args.Item2)
                    .MapAsync<(AggregateId, Seq<AggregateEvent>), (SpanResult, Outcome)>(
                        async r =>
                        {
                           // here I have to deconstruct the r and args tuples, to avoid a lot of `r.Item1` etc. 
                        })
                    .IfNone((SpanResult.AllProcessed, new Outcome.NotApplicable(args.Item2.events.Length)))
                    .Map(r => r.ToTuple())
            );
```

I find the deconstructing the tuples and the tuple return type a bit cumbersome in C#, I don't mind the `FSharpAsync.AwaitTask` so much but if there was an overload that accepts something like
`Func<string, StreamSpan<byte[]>, Task<(SpanResult, Outcome)>> handle`
I think the code would be a lot clearer?  Happy to have a go at a PR (and get some F# under my belt) if you think it would be easy enough for a beginner!

Both `StreamsProjector.Start` and `CosmosStoreSource.Start` have some optional parameters at the end of their argument list.  I can see that they are annotated with `[OptionalArgument]` from F# but my compile (using dotnet 6) still complains that the argument list is too short if I omit them.  Am I missing some interop setting that would respect the annotation?

Using the equinox libs from C# has been much easier than I thought it would be, likely due to how well thought out and documented everything is, so thanks for everyones hard work on these excellent tools :)

**Comment by bartelink** [comment]
Re the Handler signature, I have been intending to look at that so might do a first stab at adding Task sigs. Regarding:
`Aggregate.Reactions.Parse(args.Item1, args.Item2)` - can you do replace `args =>` with `(stream, span) =>` ? Maybe you need to replace `Tuple<string, StreamSpan<byte[]>` with the tuple syntax with the names? Something like `(stream : string, span : StreamSpan<byte[]>)` ?

Liking the `Seq` alias!

Hm wait.... Recent updates have replaced the `Tuple` (which is a class) with `struct` tuples which will make the above correct. What version are you using?
 (The struct tuples was prompted by perf work, but I was aware it would be nicer from C# too; hopefully over time struct tuples will be a touch less painful from F#...)

>I think the code would be a lot clearer? Happy to have a go at a PR (and get some F# under my belt) if you think it would be easy enough for a beginner!

I'm more than happy to help with PRs, so feel free to take a stab.
The best way to validate things will work in your context is to take a given project down locally, add it to your `sln`, remove the `PackageReference`s, and add refs to the project.

>Am I missing some interop setting that would respect the annotation?

if you pop this into `Propulsion.Internal`:
https://github.com/jet/equinox/blob/b0fb2e7549afbbee847dd629f31a01c2957740fd/src/Equinox.Core/Infrastructure.fs#L9-L10
then you can do `O; D null` to add the missing attributes that the F# compiler really should add
https://github.com/jet/equinox/blob/master/src/Equinox.DynamoStore/DynamoStore.fs#L1041

>StreamsProjector.Start

renamed `StreamsProjector` -> `StreamsSink` recently - there is a PR in dotnet-templates that I'll merge shortly porting to the latest https://github.com/jet/dotnet-templates/pull/126 

In general the idea is that  `Propulsion.Streams.Default.Config.Start` should cover common scenarios so it would be interesting to know what you're doing that's different. Hate the `Default` and the `Config` parts of that but have yet to think of better names.

Wait, is that because you need `byte[]` ? Is that because you are using CosmosStore3? NSJ ?

In general I'd consider the 3.0.0-beta releases pretty stable now; my main holding off was actually on adding `Task` support 

What versions are you using for Equinox? (I assume 4.0.0-rc.x; if not, the Task stuff should help there...)

**Comment by benjstephenson** [comment]
Looks like we're still on 3.0.7 for the equinox libs and 2.12.2 for propulsion; will see if I can get us on the rc versions, I'm not sure what stance the project I'm on takes for pre-release versions yet.

The `byte[]` parts I just went with what I saw in the F# example code from the template repo but there's a really good chance I was looking at old versions of stuff -  I basically just pass the `byte[]` to the json codec for the aggregate events.

I'll update to the latest rc versions and see what I end up rewriting and update here :)

**Comment by bartelink** [comment]
The Equinox and FsCodec libs are pretty ready to roll over to non-rc versions, but it would be nice to hear more people using them successfully in prod; can't always assume no news is good news ;)

(The FsCodec and Equinox RCs shift to `ReadOnlyMemory<byte>` from `byte[]` (but `Equinox.CosmosStore` moves to `JsonElement`))

Meanwhile, I ran on our week-old snow today, which was nice after practically a week of the ground being too icy ;)

**Comment by bartelink** [comment]
WIP re Func/Task in https://github.com/jet/propulsion/pull/192

**Comment by bartelink** [comment]
Releasing a 3.0.0-rc.1 shortly, which uses Func/Task for all public APIs - you should no longer need to touch FSharpFunc/FSharpAsync from C#
Would welcome a PR to apply the `[<O; D null>]` attributes for the `?` optional args

Minor API changes and/or stragglers that align with the general structure will still be possible in the short term (but, like FsCodec and Equinox, there are no significant code changes anticipated before giving them all release version numbers once there has been sufficient positive feedback from usage in production scenarios)

**Comment by benjstephenson** [comment]
I've added a couple of those attributes and used it within my project and it all looks like it works for me.  Let me know if there's any formatting etc I should change.
